name: "Build & Release"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, 'ci-skip:')"
    steps:

# clone
    - name: Clone
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Build
      run: |
        zip -r doodle.zip . -x ".*"

# release
    - name: Hash
      id: hash
      run: |
        HASH=$(shasum doodle.zip | cut -d " " -f 1)
        echo "Exporting pack hash to $HASH"
        echo "pack_hash=$HASH" >> $GITHUB_OUTPUT

    - name: Configure Git
      run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

    - name: Tag & Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}-stable
        target_commitish: master
        files: doodle.zip
        body: |
          **commit:** ${{ github.event.head_commit.message }}
          > hash: ${{ steps.hash.outputs.pack_hash }}
